refactor: local options to the utils

diff --git a/src/venvman/utils/cpython-github/build_python_version_from_source_local b/src/venvman/utils/cpython-github/build_python_version_from_source_local
--- a/src/venvman/utils/cpython-github/build_python_version_from_source_local
+++ b/src/venvman/utils/cpython-github/build_python_version_from_source_local
@@ -7,18 +7,46 @@ get_python_bin_path() {
 
 
 version_is_branch() {
-    ${VENVMAN_UTILS_DIR}/cpython-github/version_is_branch_local $1
+    ${VENVMAN_UTILS_DIR}/cpython-github/version_is_branch_local $@
 }
 
 
 get_tag_from_version() {
-    ${VENVMAN_UTILS_DIR}/cpython-github/get_tag_from_version_local $1
+    ${VENVMAN_UTILS_DIR}/cpython-github/get_tag_from_version_local $@
 }
 
 
 
 build_python_version_from_source() {
     VERSION="$1"
+
+    case "$2" in
+        --local)
+            case "$3" in
+                "true")
+                    LOCAL=$3
+                    ;;
+                "false")
+                    LOCAL=$3
+                    ;;
+                *)
+                    echo "ERROR: build_python_version_from_source --local must be true for false"
+                    return 1
+                    ;;
+            esac
+            ;;
+        *)
+            if [ -n "$2" ]; then
+                echo "ERROR build_python_version_from_source: invalid input $2"
+                return 1
+            fi
+            ;;
+    esac
+
+    if [ -z $LOCAL ]; then
+        echo "ERROR: build_python_version_from_source --local is missing"
+        return 1
+    fi
     
     if BIN_PATH=$(get_python_bin_path $VERSION); then
         echo "python${VERSION} already exists at ${BIN_PATH}"
@@ -68,7 +96,7 @@ build_python_version_from_source() {
     fi
 
     if [ "$NUM_PARTS" = 2 ]; then
-        if version_is_branch "$VERSION"; then
+        if version_is_branch "$VERSION" --local $LOCAL; then
             BRANCH=$VERSION
         fi
 
@@ -76,7 +104,7 @@ build_python_version_from_source() {
         return 1
     fi
 
-    TAG=$(get_tag_from_version "$VERSION") || return 1
+    TAG=$(get_tag_from_version "$VERSION" --local $LOCAL) || return 1
 
     CHECKOUT=$([ -n "$BRANCH" ] && echo "$BRANCH" || echo $TAG)
 
diff --git a/src/venvman/utils/cpython-github/get_tag_from_version_local b/src/venvman/utils/cpython-github/get_tag_from_version_local
--- a/src/venvman/utils/cpython-github/get_tag_from_version_local
+++ b/src/venvman/utils/cpython-github/get_tag_from_version_local
@@ -14,21 +14,33 @@ is_integer() {
 get_tag_from_version() {
     VERSION=$1
     
-    LOCAL=true
     case "$2" in
         --local)
-            LOCAL=true
-            ;;
-        --remote)
-            LOCAL=false
+            case "$3" in
+                "true")
+                    LOCAL=$3
+                    ;;
+                "false")
+                    LOCAL=$3
+                    ;;
+                *)
+                    echo "ERROR: get_tag_from_version --local must be true for false" >&2
+                    return 1
+                    ;;
+            esac
             ;;
         *)
             if [ -n "$2" ]; then
-                echo "ERROR get_tag_from_version: invalid input $2"
+                echo "ERROR get_tag_from_version: invalid input $2" >&2
                 return 1
             fi
             ;;
     esac
+
+    if [ -z "$LOCAL" ]; then
+        echo "ERROR: get_tag_from_version --local is missing" >&2
+        return 1
+    fi
 
     VERSION_MAJOR=$(get_subversion_from_version --major "$VERSION")
     VERSION_MINOR=$(get_subversion_from_version --minor "$VERSION")
@@ -44,14 +56,18 @@ get_tag_from_version() {
     else
         github_tag_format="v$VERSION"
     fi
-    
-    if $LOCAL; then
-        ITERABLE="git tag | grep $github_tag_format"
-    else
-        ITERABLE="git ls-remote --tags ${VENVMAN_CPYTHON_REMOTE_URL}"
-    fi
 
-    for tag in $(eval $ITERABLE); do
+    if $LOCAL; then
+        current="$(pwd)"
+        cd "$VENVMAN_CPYTHON_REPO_DIR"
+        ITERABLE=$(eval "git tag | grep $github_tag_format")
+        cd "$current"
+        unset current
+    else
+        ITERABLE=$(eval "git ls-remote --tags ${VENVMAN_CPYTHON_REMOTE_URL}")
+    fi
+    
+    for tag in $ITERABLE; do
         if ! $LOCAL; then
             case "$tag" in
               *"refs/tags/${github_tag_format}"*) ;;
