refactor: cpython utils now all offer a local option to use the cpython repo cloned to your machine

diff --git a/src/venvman/utils/cpython-github/build_python_version_from_source b/src/venvman/utils/cpython-github/build_python_version_from_source
--- a/src/venvman/utils/cpython-github/build_python_version_from_source
+++ b/src/venvman/utils/cpython-github/build_python_version_from_source
@@ -7,18 +7,45 @@ get_python_bin_path() {
 
 
 version_is_branch() {
-    ${VENVMAN_UTILS_DIR}/cpython-github/version_is_branch $1
+    ${VENVMAN_UTILS_DIR}/cpython-github/version_is_branch $@
 }
 
 
 get_tag_from_version() {
-    ${VENVMAN_UTILS_DIR}/cpython-github/get_tag_from_version $1
+    ${VENVMAN_UTILS_DIR}/cpython-github/get_tag_from_version $@
 }
-
 
 
 build_python_version_from_source() {
     VERSION="$1"
+
+    case "$2" in
+        --local)
+            case "$3" in
+                "true")
+                    LOCAL=$3
+                    ;;
+                "false")
+                    LOCAL=$3
+                    ;;
+                *)
+                    echo "ERROR: build_python_version_from_source --local must be true for false"
+                    return 1
+                    ;;
+            esac
+            ;;
+        *)
+            if [ -n "$2" ]; then
+                echo "ERROR build_python_version_from_source: invalid input $2"
+                return 1
+            fi
+            ;;
+    esac
+
+    if [ -z $LOCAL ]; then
+        echo "ERROR: build_python_version_from_source --local is missing"
+        return 1
+    fi
     
     if BIN_PATH=$(get_python_bin_path $VERSION); then
         echo "python${VERSION} already exists at ${BIN_PATH}"
@@ -63,12 +90,12 @@ build_python_version_from_source() {
     NUM_PARTS=$(echo "$(echo "${VERSION_PARTS}" | wc -w)" | xargs)
 
     if [ "${#NUM_PARTS}" -ne "1" ]; then
-        echo "NUM_PARTS has len longer than 1"
+        echo "ERROR: NUM_PARTS has len longer than 1"
         return 1
     fi
 
     if [ "$NUM_PARTS" = 2 ]; then
-        if version_is_branch "$VERSION"; then
+        if version_is_branch "$VERSION" --local $LOCAL; then
             BRANCH=$VERSION
         fi
 
@@ -76,7 +103,7 @@ build_python_version_from_source() {
         return 1
     fi
 
-    TAG=$(get_tag_from_version "$VERSION") || return 1
+    TAG=$(get_tag_from_version "$VERSION" --local $LOCAL) || return 1
 
     CHECKOUT=$([ -n "$BRANCH" ] && echo "$BRANCH" || echo $TAG)
 
@@ -160,4 +187,4 @@ build_python_version_from_source() {
 }
 
 
-build_python_version_from_source "$1"
+build_python_version_from_source "$@"
diff --git a/src/venvman/utils/cpython-github/get_tag_from_version b/src/venvman/utils/cpython-github/get_tag_from_version
--- a/src/venvman/utils/cpython-github/get_tag_from_version
+++ b/src/venvman/utils/cpython-github/get_tag_from_version
@@ -13,6 +13,34 @@ is_integer() {
 
 get_tag_from_version() {
     VERSION=$1
+    
+    case "$2" in
+        --local)
+            case "$3" in
+                "true")
+                    LOCAL=$3
+                    ;;
+                "false")
+                    LOCAL=$3
+                    ;;
+                *)
+                    echo "ERROR: get_tag_from_version --local must be true for false" >&2
+                    return 1
+                    ;;
+            esac
+            ;;
+        *)
+            if [ -n "$2" ]; then
+                echo "ERROR get_tag_from_version: invalid input $2" >&2
+                return 1
+            fi
+            ;;
+    esac
+
+    if [ -z "$LOCAL" ]; then
+        echo "ERROR: get_tag_from_version --local is missing" >&2
+        return 1
+    fi
 
     VERSION_MAJOR=$(get_subversion_from_version --major "$VERSION")
     VERSION_MINOR=$(get_subversion_from_version --minor "$VERSION")
@@ -29,18 +57,28 @@ get_tag_from_version() {
         github_tag_format="v$VERSION"
     fi
 
-    for tag in $(git ls-remote --tags ${VENVMAN_CPYTHON_REMOTE_URL}); do
+    if $LOCAL; then
+        current="$(pwd)"
+        cd "$VENVMAN_CPYTHON_REPO_DIR"
+        ITERABLE=$(eval "git tag | grep $github_tag_format")
+        cd "$current"
+        unset current
+    else
+        ITERABLE=$(eval "git ls-remote --tags ${VENVMAN_CPYTHON_REMOTE_URL}")
+    fi
+    
+    for tag in $ITERABLE; do
+        if ! $LOCAL; then
+            case "$tag" in
+              *"refs/tags/${github_tag_format}"*) ;;
+              *) tag= ;;
+            esac
 
-        case "$tag" in
-          *"refs/tags/${github_tag_format}"*) ;;
-          *) tag= ;;
-        esac
-
-        if [ -z $tag ];then
-            continue
+            if [ -z $tag ];then
+                continue
+            fi
+            tag=${tag##*/}
         fi
-
-        tag=${tag##*/}
 
         _VERSION_MAJOR=$(get_subversion_from_version --major "$tag")
         if [ "$VERSION_MAJOR" != "$_VERSION_MAJOR" ]; then
@@ -78,7 +116,6 @@ get_tag_from_version() {
                 return 0
             fi
         fi
-        
     done
 
     if [ "$FIND_BIGGEST" = 1 ] && [ -n "$TAG" ]; then
