refactor: breaking apart the build python util

diff --git a/src/utils/cpython-github/build_python_version_from_source b/src/utils/cpython-github/build_python_version_from_source
--- a/src/utils/cpython-github/build_python_version_from_source
+++ b/src/utils/cpython-github/build_python_version_from_source
@@ -16,6 +16,11 @@ get_tag_from_version() {
 }
 
 
+verify_cpython_repo() {
+    ${VENVMAN_UTILS_DIR}/cpython-github/verify_cpython_repo
+}
+
+
 build_python_version_from_source() {
     VERSION="$1"
 
@@ -56,14 +61,14 @@ build_python_version_from_source() {
 
         *)
             if [ -n "$2" ]; then
-                echo "ERROR build_python_version_from_source: invalid input $2"
+                echo "ERROR build_python_version_from_source: invalid input $2" >&2
                 return 1
             fi
             ;;
     esac
 
     if [ -z $LOCAL ]; then
-        echo "ERROR: build_python_version_from_source --local is missing"
+        echo "ERROR: build_python_version_from_source --local is missing" >&2
         return 1
     fi
     
@@ -72,50 +77,21 @@ build_python_version_from_source() {
         return 0
     fi
     
-    if [ ! -d "$VENVMAN_CPYTHON_REPO_DIR" ]; then
-        echo
-        echo "The repo "$VENVMAN_CPYTHON_REMOTE_URL" was not found at ${VENVMAN_CPYTHON_REPO_DIR}."
-        echo "To continue, it must be cloned to that location."
-        printf "Would you like to clone the repo and continue now? [y/N]: "
-        read -r response
-        case "$response" in
-            Y|y)
-                mkdir -p ${VENVMAN_CPYTHON_REPO_DIR}
-                git clone ${VENVMAN_CPYTHON_REMOTE_URL} ${VENVMAN_CPYTHON_REPO_DIR}
-                mkdir -p ${VENVMAN_PYTHON_BUILDS_DIR}
-                ;;
-            *)
-                echo "Exiting. The ${VENVMAN_CPYTHON_REMOTE_URL} needs to be cloned to continue."
-                return 0
-                ;;
-        esac
-
-    elif [ ! -d "$VENVMAN_CPYTHON_REPO_DIR/.git" ]; then
-        echo "ERROR: "$VENVMAN_CPYTHON_REPO_DIR/.git" is not found" >&2
-        return 1
-    fi
+    verify_cpython_repo || return 1
 
     MY_PWD="$(pwd)"
-
     cd $VENVMAN_CPYTHON_REPO_DIR || return 1
 
-    if [ "$(git remote get-url origin)" != "${VENVMAN_CPYTHON_REMOTE_URL}" ]; then
-        echo "The remote repo at ${VENVMAN_CPYTHON_REPO_DIR} does not match ${VENVMAN_CPYTHON_REMOTE_URL}" >&2
-        echo "Remote at ${VENVMAN_CPYTHON_REPO_DIR}: $(git remote get-url origin)" >&2
-        return 1
-    fi
-
-    git checkout main > /dev/null 2>&1
-    git reset --hard origin/main > /dev/null 2>&1
-    git pull > /dev/null 2>&1
 
     VERSION_PARTS=$(echo "${VERSION}" | tr '.' ' ')
     NUM_PARTS=$(echo "$(echo "${VERSION_PARTS}" | wc -w)" | xargs)
 
     if [ "${#NUM_PARTS}" -ne "1" ]; then
-        echo "ERROR: NUM_PARTS has len longer than 1"
+        echo "ERROR: NUM_PARTS has len longer than 1" >&2
         return 1
     fi
+
+    git fetch --all --tags
 
     if [ "$NUM_PARTS" = 2 ]; then
         if version_is_branch "$VERSION" --local $LOCAL; then
@@ -170,12 +146,12 @@ build_python_version_from_source() {
     git reset --hard "$CHECKOUT" || return 1
 
     if [ ! -f "./configure" ]; then
-        echo "./configure is missing"
+        echo "ERROR: ./configure is missing" >&2
         return 1
     fi
 
     if [ ! -f "./Makefile.pre.in" ]; then
-        echo "Makefile.pre.in is missing"
+        echo "ERROR: Makefile.pre.in is missing" >&2
         return 1
     fi
 
@@ -192,6 +168,11 @@ build_python_version_from_source() {
     ./configure --prefix="${VENVMAN_PYTHON_BUILDS_DIR}/${VERSION}" || return 1
     if [ $(command -v nproc &> /dev/null) ]; then
         make -j$(nproc) || cd $MY_PWD && return 1
+    elif [ $(command -v sysctl &> /dev/null) ]; then
+        ncpu=$(sysctl -n hw.ncpu)
+        if [ -n "$ncpu" ]; then
+            make -j${ncpu} || cd $MY_PWD && return 1
+        fi
     else
         make || cd $MY_PWD return 1
     fi
